import os

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(PROJECT_ROOT, "data")

BANDPASS_FREQMIN = 1.0
BANDPASS_FREQMAX = 20.0
BANDPASS_ORDER = 4

STA_WINDOW_SEC = 1.0
LTA_WINDOW_SEC = 10.0
P_THRESHOLD = 3.5
S_THRESHOLD = 2.5

S_SEARCH_OFFSET_SEC = 0.5
S_SEARCH_WINDOW_SEC = 15.0

GRID_NX = 20
GRID_NY = 20
GRID_NZ = 10
GRID_X_KM = 100.0
GRID_Y_KM = 100.0
GRID_Z_KM = 50.0

DAMPING = 0.1
SMOOTHING = 0.05
MAX_ITERATIONS = 50

ISOVALUE_LOW = -0.3
ISOVALUE_HIGH = 0.3
